name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code. 
      uses: actions/checkout@v1