name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code. 
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: sudo apt-get install libgtest-dev libboost-dev cmake clang-tidy clang-format doxygen ninja-build python3 python3-venv python3-pip libgmock-dev

    - name: Initialisation
      run: |
        make docs-init
        . venv/bin/activate
        make init

    - name: Build Tests
      run: make build-test

    - name: Execute Tests
      run: make exec-test