name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

jobs:
  Checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout code. 
      uses: actions/checkout@v1
  Initialise-Build:
    needs: Checkout
    runs-on: self-hosted
    steps:
    - name: Initialise and build the project.
      run: |
        make docs-init
        . venv/bin/activate
        make init
    - name: Build sqlwizardry
      run: make build
  Execute-Tests:
    needs: Initialise-Build
    runs-on: self-hosted
    steps:
    - name: Build tests
      run: |
        make tests  
